
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 06 00:28:12 GMT-03:00 2015
//----------------------------------------------------

package sermat.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int NUM = 11;
  public static final int RIGHT_PAR = 4;
  public static final int COLON = 5;
  public static final int STR = 16;
  public static final int TRUE = 13;
  public static final int NULL = 15;
  public static final int LEFT_PAR = 3;
  public static final int RIGHT_BRACK = 9;
  public static final int EOF = 0;
  public static final int LEFT_BRACK = 8;
  public static final int FALSE = 14;
  public static final int ID = 12;
  public static final int error = 1;
  public static final int COMMA = 2;
  public static final int RIGHT_BRACE = 7;
  public static final int LEFT_BRACE = 6;
  public static final int EQUALS = 10;
}

